server :
 port : 80
eureka :
  instance:
    hostname: localhost
  client :
   registerWithEureka : false
   fetchRegistry : false
  server : 
   waitTimeInMsWhenSyncEmpty : 10
  serviceUrl:
   defaultZone: http://localhost:80
